//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class actif
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actif()
        {
            this.CID_actif = new HashSet<CID_actif>();
            this.vulnerabilte = new HashSet<vulnerabilte>();
        }

        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public int id_actif { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string nom_actif { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy hh:mm}")]

        public Nullable<System.DateTime> date_creation_actif { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string descr_actif { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string categ_actif { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string matricule { get; set; }
        public string errorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CID_actif> CID_actif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vulnerabilte> vulnerabilte { get; set; }
        public virtual collaborateur collaborateur { get; set; }
    }
}
