//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class action
    {
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public int id_action { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string nom_action { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string description_action { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string échéance { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string etat_avancement { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string commentaire { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string matricule_responable { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public Nullable<int> id_gestion_risk { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy hh:mm }")]
        public Nullable<System.DateTime> date_creation { get; set; }
        public string errorMessage { get; set; }
        public virtual gestion_risque gestion_risque { get; set; }
    }
}
