//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class action
    {
        public int id_action { get; set; }
        public string nom_action { get; set; }
        public string description_action { get; set; }
        public string échéance { get; set; }
        public string etat_avancement { get; set; }
        public string commentaire { get; set; }
        public string matricule_responable { get; set; }
        public Nullable<int> id_gestion_risk { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public Nullable<int> id_mesure { get; set; }
    
        public virtual gestion_risque gestion_risque { get; set; }
        public virtual action_mesure action_mesure { get; set; }
    }
}
