//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public activite()
        {
            this.CID_actif = new HashSet<CID_actif>();
        }
    
        public int id_activite { get; set; }
        public string nom_activite { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public string matricule { get; set; }
    
        public virtual collaborateur collaborateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CID_actif> CID_actif { get; set; }
    }
}
