//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CID_actif
    {
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public int id_activite { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public int id_actif { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public Nullable<int> id_confid { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public Nullable<int> id_integ { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public Nullable<int> id_dispo { get; set; }
        public string errorMessage { get; set; }

        public virtual actif actif { get; set; }
        public virtual activite activite { get; set; }
        public virtual confid confid { get; set; }
        public virtual disponibilte disponibilte { get; set; }
        public virtual integrite integrite { get; set; }
    }
}
