//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CID_actif
    {
        public int id_activite { get; set; }
        public int id_actif { get; set; }
        public Nullable<int> id_confid { get; set; }
        public Nullable<int> id_integ { get; set; }
        public Nullable<int> id_dispo { get; set; }
    
        public virtual actif actif { get; set; }
        public virtual confid confid { get; set; }
        public virtual disponibilte disponibilte { get; set; }
        public virtual integrite integrite { get; set; }
        public virtual activite activite { get; set; }
    }
}
