//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collaborateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public collaborateur()
        {
            this.actif = new HashSet<actif>();
            this.activite = new HashSet<activite>();
        }
    
        public string matricule { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string fonction { get; set; }
        public string CIN { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date_Naissance { get; set; }
        public string Adresse { get; set; }
    
        public virtual user_table user_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actif> actif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activite> activite { get; set; }
    }
}
