//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class collaborateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public collaborateur()
        {
            this.activite = new HashSet<activite>();
            this.actif = new HashSet<actif>();
        }

        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string matricule { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string nom { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string prenom { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string fonction { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string CIN { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]

        public Nullable<System.DateTime> Date_Naissance { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string Adresse { get; set; }
        public string errorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activite> activite { get; set; }
        public virtual user_table user_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actif> actif { get; set; }
    }
}
