//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class gestion_risque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gestion_risque()
        {
            this.action = new HashSet<action>();
        }
    
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public int id_gestion_risk { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string nom_gesion_risk { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string description_gestion_risk { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy hh:mm}")]
        public Nullable<System.DateTime> date_creation_g_risk { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string risk_dicision { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public Nullable<int> id_vulne { get; set; }
        public string errorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<action> action { get; set; }
        public virtual vulnerabilte vulnerabilte { get; set; }
    }
}
