//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class impact
    {
        public int id_impact { get; set; }
        public string nom_impact { get; set; }
        public Nullable<System.DateTime> date_creation_impact { get; set; }
        public string descr_impact { get; set; }
        public Nullable<int> score_impact { get; set; }
        public Nullable<int> id_menace { get; set; }
    
        public virtual menace menace { get; set; }
    }
}
