//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class integrite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public integrite()
        {
            this.CID_actif = new HashSet<CID_actif>();
        }
    
        public int id_integ { get; set; }
        public string nom_integ { get; set; }
        public Nullable<System.DateTime> date_creation_integ { get; set; }
        public string descr_integ { get; set; }
        public string score_integd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CID_actif> CID_actif { get; set; }
    }
}
