//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menace()
        {
            this.impact = new HashSet<impact>();
            this.prob_occurrence = new HashSet<prob_occurrence>();
        }
    
        public int id_menace { get; set; }
        public string nom_menace { get; set; }
        public Nullable<System.DateTime> date_creation_menace { get; set; }
        public string desc_menace { get; set; }
        public Nullable<int> id_vulne { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<impact> impact { get; set; }
        public virtual vulnerabilte vulnerabilte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prob_occurrence> prob_occurrence { get; set; }
    }
}
