//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prob_occurrence
    {
        public int id_occur { get; set; }
        public string nom_occur { get; set; }
        public Nullable<System.DateTime> date_creation_occur { get; set; }
        public string desc_occur { get; set; }
        public Nullable<int> score_occur { get; set; }
        public Nullable<int> id_menace { get; set; }
    
        public virtual menace menace { get; set; }
    }
}
