//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class prob_occurrence
    {
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public int id_occur { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string nom_occur { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy hh:mm}")]
        public Nullable<System.DateTime> date_creation_occur { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string desc_occur { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        [Range(0, 5, ErrorMessage = "Veuillez Entrer Un Score Correct")]
        public Nullable<int> score_occur { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public Nullable<int> id_menace { get; set; }
        public string errorMessage { get; set; }

        public virtual menace menace { get; set; }
    }
}
