//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user_table
    {
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string matricule { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string username { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string passeword { get; set; }
        public string errorMessage { get; set; }
        public virtual collaborateur collaborateur { get; set; }
    }
}
