//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table
    {
        public string matricule { get; set; }
        public string username { get; set; }
        public string passeword { get; set; }
    
        public virtual collaborateur collaborateur { get; set; }
    }
}
