//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSI_ISO27005.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vulnerabilte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vulnerabilte()
        {
            this.menace = new HashSet<menace>();
            this.gestion_risque = new HashSet<gestion_risque>();
        }

        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public int id_vulne { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string nom_vulne { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy hh:mm}")]
        public Nullable<System.DateTime> date_creation_vulne { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public string desc_vulne { get; set; }
        [Required(ErrorMessage = "Ce Champs Et Obligatoire")]
        public Nullable<int> id_actif { get; set; }
        public string errorMessage { get; set; }

        public virtual actif actif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menace> menace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gestion_risque> gestion_risque { get; set; }
    }
}
